### PR TITLE
enabling joint training for VQVAE and DQN

### PR DESCRIPTION
**Pull request by manncodes**
Proposed:
- addition of new `train_both` method that trains both in one gradient step.

### CODE REVIEW

**Comment by manncodes** [comment]
@jonzamora review please

**Comment by jonzamora** [comment]
Hi Mann,

The code in `vqn.py` looks good to me.

1 change i'd like you to implement: 

- [ ] Please modify the code in `vqn_main.py` to use a boolean flag, which you can call `--train_both`, so we can easily alternate between using the `train_both` method and the original 2-stage method.

**Comment by manncodes** [comment]
shouldn't i rather make a FLAG that can be used by passing as args from sh?

**Comment by jonzamora** [comment]
yea, that's what i meant.

**Comment by manncodes** [comment]
doesn't brakes on colab. LGTM

**Pull request merged**
